#ifndef BRAINRINGLIB_GLOBAL_H
#define BRAINRINGLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BRAINRINGLIB_LIBRARY)
#  define BRAINRINGLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BRAINRINGLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BRAINRINGLIB_GLOBAL_H
